apiVersion: v1
kind: Pod
metadata:
  name: hello-world-flask
spec:
  containers:
    - name: flask
      image: huangxuantao/hello-world-flask
      ports:
        - containerPort: 5000

    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
