name: build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  DOCKERHUB_USERNAME: huangxuantao

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        